### ISSUE TITLE
[BUG] mobile navigation

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#106]
I think we should put socials inside the nav when mobile.

I prefer having the menu in full width ? and the close icon at right ?

What do you think @aurelienroux

**Comment by f3ltron** [comment]
maybe add a transition with the transition component to close and open menu too ?

**Comment by aurelienroux** [comment]
@f3ltron agreed with that. If menu is 100% all the time, transitioning is going to be easier to do. 
I'm on it
