### ISSUE TITLE
[HOME] We want to push / show event incoming

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#109]
as we will have new events we can check if the first event is in the futur so it will be the next one.

Maybe a red border. I don't know for now so if you have any ideas.

**Comment by jeremiebardon** [comment]
Interested to play with this one :)

**Comment by f3ltron** [comment]
Sure i assign you :). Tell me if you have any idea how you see this

**Comment by f3ltron** [comment]
you can use the date in storyblok event
