### ISSUE TITLE
[FEATURE] [next events] [creation process]

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#11]
Actually i define the next events coming just base on the order of the json files archives read.

It mean : 
- if the event is pass it will be here

how we can improve 👍 
- We should create a component to show if no events coming
- We should base on date to know if an events incoming or base on the done true / false inside the json. Or maybe the json true false is useless

**Comment by T0RAT0RA** [comment]
@f3ltron I started a rewrite of the event pages creation.
I'm still learning vuepress, but looks like the magic happens in `blog/.vuepress/plugins/index.js`.
I tried to reduced the complexity as much as possible, see my comments in the PR.

**Comment by f3ltron** [comment]
Sure :). I will have a look on it. Yeah all its coming form here ask if you have any questions

**Comment by f3ltron** [comment]
The idea behind is. 

Actually:
- We list the files inside archives.
- i use the date writtend as a filename to organize them
- from here i use the latest as the upcoming event

The idea is to list them and use the data inside and just it to tree shake them
