### ISSUE TITLE
[JOB] adding list page of company that works on vuejs

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#118]
We have to think about creating some figma design something clear.

We want to have like a pr or a forms for company who want to join the list

we will add them from storyblok so it will be easy to add and delete companies

the object could be:

company: {
name: String,
location: String
description: For the project they are using it
stack description: What the env for the vuejs dev
}

i need your feedback on what we want i just dont want like a company description

**Comment by fuentesloic** [comment]
@f3ltron WDYT about:
```JSON
job: {
   company: String,
   position: String,
   location: [latitude: int, longitude: int],
   description String
   stack: [String, String, String]
}
```
Pour la stack il y a mm peut etre une lib avec les techno + icon ou alors on pourrait faire un liste nous mm avec un select
