### ISSUE TITLE
[JOB] What can we use / do to find company that use vuejs ?

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#119]
As Developer i would like to know wich companies are using vuejs.

Currently i don't know the best way to do that. Linkedin contacts?

Maybe we can start by listing all companies we know in montreal and ask them if they are doing vuejs ?

**Comment by jeremiebardon** [comment]
we can also use tools like snov.io, wappalyzer etc ...

**Comment by f3ltron** [comment]
The thing is we want something free. So i dont know we can start with vue jobs and think how to do after it

**Comment by aurelienroux** [comment]
did an interview at Tracktik about a year ago, and they were considering going with Vue for their FE team. Dont know if they did it or not.
Also, I'm not sure but I think some teams in Ubisoft are using Vue also. I sent a message to a friend to see if he can confirm that.
