### ISSUE TITLE
I think there is a css problem with some conflicts css

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#125]
image in event are to small 
and socials are not align in flex

**Comment by aurelienroux** [comment]
@f3ltron think I found the problem here. on navbar-left.vue component, a "scoped" attribute is missing on style declaration on line 115. Add it and it should fix the bug

**Comment by f3ltron** [comment]
can you create a branch with the correction ? If you push it it will create a tmp env in netlify with nuxt generate so we can validate
