### ISSUE TITLE
ideas to improve the design

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#136]
At the end we will add all validated ideas in the next project

**Comment by jeremiebardon** [comment]
Try to do some Design this week!

**Comment by f3ltron** [comment]
Do you need access to figma? If possible i would like to check what you tried maybe it will give me ideas too :)

**Comment by jeremiebardon** [comment]
Yep good idea!

**Comment by f3ltron** [comment]
Come to slack pm me and i will give you access to figma. You can design on it

**Comment by jeremiebardon** [comment]
> Come to slack pm me and i will give you access to figma. You can design on it
![Capture](https://user-images.githubusercontent.com/17425520/79011883-0c695680-7b33-11ea-8d0f-c5777c33819a.PNG)

Don't be invited I guess! :)

**Comment by f3ltron** [comment]
https://app.slack.com/client/TDJE5CKHP/CDJV3SA11

**Comment by aurelienroux** [comment]
@f3ltron where do we pitch the design improvement ideas ? directly on this task or on the slack channel ?
Also we should have a hover state on links and buttons

**Comment by f3ltron** [comment]
I would prefer here and you edit your post and we decid after on slack

**Comment by jeremiebardon** [comment]
1. Poppins is also a cool fonts! Montserrat is a great idea too and join the second point. 
2. Maybe more sharpness form (Button). More representative about web dev and Vue.js framework.
3. Homepage +1 with fast link for jobs, Events Live channel and sponsors. (Maybe contributor too)
4. More clarity for new and past events (Background on new events ?)
5. Fix sub-header if we scroll on event page ( with the title, join button and date).
6. Maybe the lang can be on a general header on top ? What you think @aurelienroux

**Comment by jeremiebardon** [comment]
It's on the figma now

**Comment by aurelienroux** [comment]
@jeremiebardon @f3ltron we'll also need a design for the 404 page

**Comment by f3ltron** [comment]
@aurelienroux we are in phase of thinking so if you have any ideas or examples of 404 give us on figma 👍
