### ISSUE TITLE
[FEATURE] add sponsors

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#20]
add sponsors to:

- events pages if exist
- home page

gsquad / Atecna

**Comment by f3ltron** [comment]
get the logo of both and put them in events and home page

**Comment by f3ltron** [comment]
image for atecna https://uploads-ssl.webflow.com/5d1ba5da16604d65206a3912/5d1bcc2073eabc3d50559008_Logo%20Atecna%20inline.svg

**Comment by pjawneh** [comment]
is this the gsquad logo you're referring to?
https://www.gsquad.com/assets/website/logos/full-logo-4a170f8d2409d2d0ba3dfebb66321c75589cc09075f19a1ac0277867887ee2fe.svg

**Comment by f3ltron** [comment]
yes 👍

**Comment by f3ltron** [comment]
Atecna supported last events September the 25h
And gsquad two first events.

Add h1 with 

Thank's for sponsoring:

Sponsor image with a link to their website
