### ISSUE TITLE
[module] Add validator modules.

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#23]
It should create a nuxt hook before dev and generate.

This hook shoold validate or not the events files formats.

We should have a great log on console when error

**Comment by T0RAT0RA** [comment]
If the events are statics files, we could have unit tests instead, so it would be validated before merging the code, what do you think?

**Comment by T0RAT0RA** [comment]
Also, isn't this issue a duplicate of https://github.com/vuemontreal/vuemontreal/issues/24 (if it's only about event format)?

**Comment by f3ltron** [comment]
Sure we should add it to the commit workflow. It's connected yes with #24 but the 24 is more for validate the data model of an event more than create the validator in the commit workflow

**Comment by f3ltron** [comment]
same as #24
