### ISSUE TITLE
[configuration] Validate events formats.

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#24]
Currently events have a classic format with fr and en key that will match the current locale.

Check a file

**Comment by f3ltron** [comment]
events should have a header property to update SEO

**Comment by T0RAT0RA** [comment]
Do you think about unit tests that will validate all events data at the PR level?

**Comment by f3ltron** [comment]
definitely yes

**Comment by f3ltron** [comment]
but this ticket is more to create a data model

**Comment by f3ltron** [comment]
as we will use storyblok dont need to validate it anymore
