### ISSUE TITLE
What subjects would you like to hear about

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#26]
Explain here which subjects you like to hear about and upvote it

**Comment by aurelienroux** [comment]
Just throwing an idea and don't know if it there would be enough material but I'd like to learn more about the different implementations of Vuejs. 
From what I understand, Vue can be used in any basic html project just by importing it from a cdn. I found it interesting as it is a huge advantage vs react and angular where you need all the webpack, cli and stuff at a minimum. And as for now, I only saw the implementation with Vue-cli. 
but then again, not sure if there is enough material for an entire talk 😃
