### ISSUE TITLE
[configuration] adding Storybook for ui library

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#27]

**Comment by T0RAT0RA** [comment]
What will be the UI library? Are we talking of an existing one (buefy, vuetify, etc..) or an homade one?
What will Storybook be used for?

**Comment by f3ltron** [comment]
the ui library will be tailwind. I am not sure we will use storybook for that project maybe a bit overrated.

**Comment by f3ltron** [comment]
just to know storybook is for building a design system
