### ISSUE TITLE
[configuration] migrate old events for new format

### ISSUE THREAD

**Issue by f3ltron** [vuemontreal/vuemontreal#38]

**Comment by T0RAT0RA** [comment]
Is this the new format: https://github.com/vuemontreal/vuemontreal/blob/vuemontreal-next/events/event006.js?

**Comment by T0RAT0RA** [comment]
I created a small script to migrate old event to the new format:
https://gist.github.com/T0RAT0RA/cb403ee35195d54225bd9dba73bce25a

```
node migrate-old-events.js old_events/*
```

![image](https://user-images.githubusercontent.com/5289520/75407879-17995780-58e2-11ea-81c8-e37451a8d0ef.png)


It will parse each event file given as the command argument and create a corresponding json file in the new format.

Notes:
- I didn't see where to find the `global.image` value from the old format.
- I can't assign the issue to me

**Comment by f3ltron** [comment]
Yes it will be the new format i will come back to you with a data model i thought
